server:
  port: 80

spring:
  application:
    name: liazhan-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service_member
          uri: lb://LIAZHAN-MEMBER
          order: 0
          predicates:
            - Path=/liazhan-member/**
          filters:
            - StripPrefix=1

        - id: service_weixin
          uri: lb://LIAZHAN-WEIXIN
          order: 0
          predicates:
            - Path=/liazhan-weixin/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: debug



